# Rails.application.routes.draw do
#   # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

#   # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
#   # Can be used by load balancers and uptime monitors to verify that the app is live.
#   get '*path', to: 'homepage#index', constraints: ->(request) { request.format.html? }
#   root 'homepage#index'
#   namespace :api do
#     resources :art_pieces, only: [:index, :show] #model name is ArtPiece, rails conventionally pluralizes model names when defining routes,
#     # so art_pieces would generate RESTful routes for CRUD operations related to the ArtPiece Model
#     # endonly:[:index, :show] restricts the routes generated by resources to only the index and show actions
#   end
# end

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  devise_for :users

  namespace :api do
    resources :art_pieces, only: [:index, :show] do #api/art_pieces/
    end

    resources :users do
      resources :flowers
      resources :moods
    end

    resources :journals, only: [:create, :index, :show]

  end




 # Define resources for moods if you haven't already
 resources :moods, only: [:index]

 # Add a custom route for select_mood action
 post 'select_mood', to: 'moods#select_mood'

 # Define homepage path
 get 'homepage', to: 'home#index', as: 'homepage'
  
end
